---
title: "Animal Crossing in R"
output: html_notebook
---

```{r}
library(tidyverse)

# Get the Data
critic <- readr::read_tsv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-05/critic.tsv')
user_reviews <- readr::read_tsv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-05/user_reviews.tsv')
items <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-05/items.csv')
villagers <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-05/villagers.csv')
print(villagers)
```

```{r}
villagers
items %>%
  View()
```


### Text Analysis

```{r}
critic %>%
  ggplot(aes(grade)) +
  geom_histogram()

user_reviews %>%
  ggplot(aes(grade)) +
  geom_histogram()

head(user_reviews$text)
```

```{r}
library(tidytext)
library(lubridate)

user_reviews %>%
  group_by(week = floor_date(date, "week")) %>%
  summarize(nb_reviews = n(),
            avg_grade = mean(grade))

# on a day a user used this word n number of times
user_review_words <- user_reviews %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words, by = "word") %>%
  count(user_name, date, grade, word)

```
```{r}

```

```{r}
# what words were associated with what reviews filtered by high frequency ordered by high grade
user_review_words %>%
  group_by(word) %>%
  summarize(avg_grade = mean(grade),
            nb_reviews = n()) %>%
  arrange(desc(nb_reviews)) %>%
  filter(nb_reviews >= 50) %>%
  arrange(desc(avg_grade))


user_reviews %>% filter(str_detect(text, 'bombing')) %>% View()
```

